name: Prettier
on: [pull_request]
jobs:
  prettier-check:
    name: "Run Prettier"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: "latest"
      - run: pnpm install
      - run: pnpm exec prettier . --check
